spring:
  flyway:
    user: root
    password: password
    url: jdbc:mysql://localhost:3306/projectdb
    baseline-on-migrate: true
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/projectdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5