spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://wht-mysql:3306/projectdb
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  flyway:
    user: ${spring.datasource.user}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    baseline-on-migrate: true