spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3600/projectdb
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  flyway:
    user: root
    password: password
    url: jdbc:mysql://localhost:3306/projectdb
    baseline-on-migrate: true