spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  profiles:
    active: test
  application:
    name: catalog-service
    config:
      import: 'optional:configserver:'
  sql:
    init:
      mode: always
management:
  endpoint:
    web:
      exposure:
        include: refresh
server:
  port: 9001